# Generated by Django 2.2.12 on 2023-04-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220911_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userjjy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.IntegerField()),
                ('info', models.CharField(default='111', max_length=32)),
                ('hobby', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.CharField(default='111', max_length=32),
        ),
    ]
