# Generated by Django 2.2.12 on 2023-04-04 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20230404_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjjy',
            old_name='username',
            new_name='username123123',
        ),
    ]
